### ISSUE TITLE
is the addon suppose to remember which tabs i had reloader active on btw reboot?

### ISSUE THREAD

**Issue by seasaltseasalt** [james-fray/tab-reloader#1]
Hello:
is the addon suppose to remember which tabs i had reloader active on btw reboot?
because it currently is not for me. 

---
Fx 41.0.2 on OSX yosemite 10.10

I use the addon session manager too. So not sure if that makes a difference to your addon behaviour on reload.
Thankyou

**Comment by james-fray** [comment]
Currently there is no history on browser reboot. We might have this in the future

**Comment by Banditz71** [comment]
I too would "really" like to see this feature added.......it's sort of a pain having to reset everything every time the browser is closed and re-opened.  LOVE the addon!  Thanks!

**Comment by DanLot** [comment]
I'd appreciate cross-session saving too!

**Comment by james-fray** [comment]
This is fixed on 0.1.2. Thanks for the report. Read FAQ 8 for more info about the limitations; http://add0n.com/tab-reloader.html
