### ISSUE TITLE
Feature request: disable reload if current public IP doesn't follow the rule

### ISSUE THREAD

**Issue by GCRaistlin** [james-fray/tab-reloader#100]
Some torrent trackers forbid to be visited through VPN. If such torrent tracker tab is reloading during the VPN session user can get banned.
I believe the following option would be useful (_{a|b}_ means drop-down list with elements _a_ and _b_):

`{Reload | Don't reload} tabs if current public IP {is | isn't} {any | n/a | [list of IP masks]} {AND|OR} {is | isn't} {any | n/a | [list of IP masks]}`

The first values are defaults (i. e. ignore IP - the current behaviour}.
The second rule would allow to disable reload if no Internet connection is present, like:
Reload if current public IP isn't _ip_mask_ AND isn't n/a.

**Comment by james-fray** [comment]
This is something you can achieve with the custom script. Find a free service that returns the IP. If this IP does not match the stored one, trigger a `new Event('toggle-requested')` event.
