### ISSUE TITLE
What does "Resume previously active jobs" actually do?

### ISSUE THREAD

**Issue by GCRaistlin** [james-fray/tab-reloader#101]
I cannot understand what this action does. What's the difference from "Resume all"?

**Comment by james-fray** [comment]
> "Resume previously active jobs"

I am updating the extension to make it compatible with manifest v3. There are many UX and background changes. This function is also removed.

**Comment by mjeveritt** [comment]
How do we re-activate 'lost' jobs resulting from this UI change? Is it now 'lost' from the plugin config too?

FYI, regressions with no workaround/upgrade path are generally undesirable ..

**Comment by james-fray** [comment]
> How do we re-activate 'lost' jobs resulting from this UI change? Is it now 'lost' from the plugin config too?

Can you explain what has been lost?

**Comment by mjeveritt** [comment]
> > How do we re-activate 'lost' jobs resulting from this UI change? Is it now 'lost' from the plugin config too?
> 
> Can you explain what has been lost?

Previously, if restarting/suspending/reloading browser and/or tabs, you could reinstate the timers from a previous/saved session/config.
Eg. I use 'Tab Session Manager' to save my browser tabs/windows between sessions, and this doesn't always play nice with the Tab-Reloader plugin when it reinstates an old session. You could previously hit the Reloader icon and select 'Restore previous reloading jobs' (and/or Resume all jobs, Resume previously active jobs too) from the drop-down menu to get these jobs 'back' and the icon would change from default grey to orange with the number of active jobs again. This doesn't seem to apply to the newer versions, as the plugin drop-down no longer has any plugin-specific functions in it.
Does this make sense, or am I describing it badly!? :D

**Comment by james-fray** [comment]
@mjeveritt This is a valid use case. On the "0.5.0.7" release, the extension resumes broken jobs whenever a new tab with the same URL is loaded. Broken jobs are those that have not been turned off by the user from the extension's interface.

I guess this fixes the integration issue with session manager extensions.

**Comment by mjeveritt** [comment]
> @mjeveritt This is a valid use case. On the "0.5.0.7" release, the extension resumes broken jobs whenever a new tab with the same URL is loaded. Broken jobs are those that have not been turned off by the user from the extension's interface.
> 
> I guess this fixes the integration issue with session manager extensions.

Thanks! Have you got a release in process, is there possibly a beta package I could test and verify for you?! :smiley:

**Comment by james-fray** [comment]
It is submitted to the WebStore. You can also try the https://github.com/james-fray/tab-reloader/tree/master/v3

**Comment by mjeveritt** [comment]
The other thing the "Resume previously active" did was to resume/start all the Reload timers for each [cached/stored] page. I see the [correct] timer setting is getting loaded now, but I have to manually activate each page .. which is tedious even for as low at 6 pages which I have always persistent .. is this something that can be re-incorporated?

**Comment by james-fray** [comment]
@mjeveritt The current version is supposed to detect and resume the old jobs after a reboot or on the first occurrence (when a new tab with the same meta is opened). But based on your comment, it seems like there are jobs that do not start automatically, right?
