### ISSUE TITLE
The count shown in the badge can be incorrect

### ISSUE THREAD

**Issue by ziffusion** [james-fray/tab-reloader#102]
Consider the use-case where one wants to reload based on a `url` regex match. One would setup a job with the `hostname` clause followed by a policy with a `url` regex clause.

Now a page that matches the `hostname` clause but not the `url` clause will show up incorrectly in the badge count - even though it will not actually be reloaded.

Most users would want the counter to reflect tabs being actually reloaded (not merely matching jobs).

**Suggestion:** allow the `url` clause in the job entries to also be a regex match instead of just equality `===`.

This would be backwards compatible with the current semantics of the `url` clause, while making it much more flexible and valuable.

**Comment by james-fray** [comment]
The recent releases of the extension support the [URLPattern matching](https://developer.mozilla.org/docs/Web/API/URL_Pattern_API) API, which pretty much deprecates the policy section, and the counter reflects the correct number of active jobs.

So the idea is to gradually get rid of the policy section to simplify the job assignment. Please reopen if if it is not clear.
