### ISSUE TITLE
Custom jobs with URL don't work

### ISSUE THREAD

**Issue by AlexWayfer** [james-fray/tab-reloader#103]
Hello.

They were working, but after some update they now don't.

```
[
  {
    "dd": 0,
    "hh": 0,
    "mm": 3,
    "ss": 0,
    "url": "*vkusvill.ru/personal/orders/?id=*"
  },
  {
    "dd": 0,
    "hh": 0,
    "mm": 5,
    "ss": 0,
    "url": "https://www.twitch.tv/directory/following"
  },
  {
    "dd": 0,
    "hh": 0,
    "mm": 5,
    "ss": 0,
    "url": "https://www.twitch.tv/directory/all"
  }
]
```

**Comment by james-fray** [comment]
Thanks for the report. Please give 0.5.0.4 a try (WebStore only)

**Comment by AlexWayfer** [comment]
How to get installed version? "Manage extension" page shows only "Version 0.5.0".

This functionality still doesn't work.

**Comment by james-fray** [comment]
I just stopped distributing the 0.5.0.x releases to the users until the bugs of migrating to manifest v3 are fixed. You need to manually install the extension from WebStore.

**Comment by AlexWayfer** [comment]
OK, after manual re-installation it works, thank you.
