### ISSUE TITLE
Who told me I can get the old version on chrome

### ISSUE THREAD

**Issue by bithuc** [james-fray/tab-reloader#104]
the new version on chrome is not working for me... where can i download the old version ( stable version 5 days ago ). I have searched but I don't know where to download it.

**Comment by james-fray** [comment]
> the new version on chrome is not working for me

Can you explain what is not working? I need more info to be able to fix the bugs. Note that we eventually need to move to manifest v3. The old version simply does not work on manifest v3!

> where can i download the old version

Download the FF version from AMO

**Comment by bithuc** [comment]
I use the following code to load the subpage in the website.
I have a problem that this JS code is not working on your latest addon version in chrome. firefox is working.
`setTimeout(function(){
var urls = new Array();
urls[0] = "https://google.com";
urls[1] = "https://google.com/doodles";
var random = Math.floor(Math.random()*urls.length);
window.location = urls[random];
}, Math.floor(Math.random() * 5000));`

**Comment by james-fray** [comment]
The new version runs JS code in a sandbox context. So you cannot perform cross-origin redirects (`window.location = ...`).

The code that you provide does not open a subframe. It simply redirects to one of the URLs in the list. Anyhow if this is what you really need, use something like:

```js
setTimeout(function() {
  const urls = [
    'https://google.com',
    'https://google.com/doodles'
  ];
  const random = Math.floor(Math.random() * urls.length);
  // redirect to the destination
  const a = document.createElement('a');
  a.href = urls[random];
  a.click();
}, Math.floor(Math.random() * 5000));
```
