### ISSUE TITLE
Can we go back to the Chrome version before last week?

### ISSUE THREAD

**Issue by Taomyn** [james-fray/tab-reloader#105]
Using this with Brave (V1.34.81), now reloading tabs randomly stop reloading and also randomly do not resume reloading when the browser is restarted. Is the main options page new because it's not like I remember is I see no option to enable/disable resuming after browser restart. The new tab options window is not great either compared to before.

It was all working fine until last week.

**Comment by james-fray** [comment]
Please make sure you have the 0.5.0.4 release. From what you have explained, this is related to a bug that is fixed on this version. Note that you need to manually reinstall the extension from WebStore for now.

**Comment by Taomyn** [comment]
Thanks, that sorted me out, was still on v0.5.0.0 for some reason
