### ISSUE TITLE
if pictures change

### ISSUE THREAD

**Issue by bress78** [james-fray/tab-reloader#106]
A great add-on, thank you developer. 

I would like to use the tab-reloader to be notified by sound on a page where pictures change. Is this possible? I know nothing about JS code and I understood that if I pasted the text in the FAQ #19 into the "Run JS code" box, I would be notified by sound, but no success ... 

Your input is most appreciated! P

**Comment by james-fray** [comment]
If the image is hard-coded, the method in FAQ 19 works. If not, you need to somehow find the image with JS, compare it with the old one and generate the sound when needed.
