### ISSUE TITLE
Page refresh time

### ISSUE THREAD

**Issue by BfGanimeshnik** [james-fray/tab-reloader#107]
Hello, I wanted to know if it is possible to set it up here so that it updates, for example, from 02/03/2022 00:00 to 02/07/2022 21:00, and after 02/07/2022 21:00 it stops updating.

**Comment by james-fray** [comment]
> Hello, I wanted to know if it is possible to set it up here so that it updates, for example, from 02/03/2022 00:00 to 02/07/2022 21:00, and after 02/07/2022 21:00 it stops updating.

For complex tasks like this, you can enable reloading as usual for all days. Then have a policy rule to prevent reloading if the time range does not match.

> And I also wanted to know how to enable it in the extension files

Having the extension to start reloading without any user interaction is not in the scope of this extension.
