### ISSUE TITLE
TOR Browser

### ISSUE THREAD

**Issue by mmtka** [james-fray/tab-reloader#109]
Hello,

the Custom Jobs doesn't work for me in TOR Browser, the same code work in Mozilla Firefox. Is it known bug or something new?

**Comment by rNeomy** [comment]
I just checked the default example on the Tor browser, and it worked for me on a clean install.

--
btw, the current version on AMO is pretty much deprecated. This extension is migrated to manifest v3, which is still not supported on Firefox.
