### ISSUE TITLE
Timers randomly turn off by themselves

### ISSUE THREAD

**Issue by cracklejoy** [james-fray/tab-reloader#110]
The issue is simple.  I'll set a timer for a page refresh and this will work fine for awhile and then it will suddenly stop without any interaction from myself.

Running Brave 1.36.109 and Tab Reloader v0.5.1

I'm not sure how to troubleshoot this.  Do updates to the browser itself without a relaunch have any effect?  I'm grasping at straws here, all I am looking for is a simple nonintrusive page reloader and your work fits the bill.  This current issue is a stop stopper literally.

Thanks

**Comment by james-fray** [comment]
Can you reproduce the issue on Chrome too?

**Comment by cracklejoy** [comment]
I don't run Chrome and this might be related to tab discarding as I noticed the timers appear to be forgotten when this is invoked.

**Comment by james-fray** [comment]
It turned out that Chromium changes the id of a newly discarded tab. This fix tries to find a discarded tab with the same URL and assign it to the old reloading job.
