### ISSUE TITLE
Reload options as default

### ISSUE THREAD

**Issue by Omnibrain007** [james-fray/tab-reloader#113]
Is there an option to preset the reload-options for new websites, like "Do not reload tab if active", "Use cache..", etc. ?
Would be nice to set some of the options as active by default for new reload jobs instead of select again an again.

And second question, is there a keyboard shortcut to fast "reload all tabs" and "resume all jobs"? 
Or is it possible to put the two option in the main right click menu to have faster access?

**Comment by james-fray** [comment]
> Is there an option to preset the reload-options for new websites

On the 0.5.x release (for Chromium browsers), you can configure defaults from the options page for new websites. Also, on the first job set for a new hostname, the extension stores your preferences and offers them on subsequent popup openings on the same hostname.

**Comment by james-fray** [comment]
>  is there a keyboard shortcut to fast "reload all tabs" and "resume all jobs"?

We are going to support all context menu commands in chrome://extensions/shortcuts

<img width="703" alt="Screenshot 2022-05-09 at 03 03 18" src="https://user-images.githubusercontent.com/9897733/167357508-7c387b7b-348d-45b5-b7cc-8effc62c5b14.png">

**Comment by Omnibrain007** [comment]
Ok, but I just using the addon for Firefox 0.3.7. 
So I have to wait for an update. thx
