### ISSUE TITLE
Unloaded Tabs Should Not Be Reloaded

### ISSUE THREAD

**Issue by megamorphg** [james-fray/tab-reloader#116]
Steps to Reproduce:
1. Set a rule to reload a tab
2. Open the tab
3. Observe reload
4. Manually suspend/unload/discard the tab using native features (like Tab Discarder)
5. Observe that the tab re-loads itself

Expected Result:
After suspension, jobs should be terminated for the tab. This may need to be an option

I am using Firefox version by the way, which is much older than the latest in Chrome, not sure if this was addressed in a later version.

**Comment by james-fray** [comment]
By default, the extension keeps reloading the tab even if it is discarded. I just added a new option to ignore the job if the tab is discarded.

**Comment by james-fray** [comment]
<img width="698" alt="Screenshot 2022-05-09 at 02 37 39" src="https://user-images.githubusercontent.com/9897733/167353713-102658a0-a96f-4442-9786-26808bec95e9.png">
