### ISSUE TITLE
Fold reload policies into custom jobs

### ISSUE THREAD

**Issue by madduck** [james-fray/tab-reloader#117]
I am coming from #65 and would like to propose that the reload policies be integrated with custom jobs.

Right now, the following is required to install a reload job every time the SquashNZ website is loaded:

```
# custom job:
[
  {
    "hostname": "*squash.org.nz",
    "dd": 0,
    "hh": 0,
    "mm": 11,
    "ss": 0
  }
]

# reload policy:
{
  "*squash.org.nz": {
    "url": "^/sit/"
  }
}
```

There are a number of limitations resulting from this:

1. It's redundant in that the hostname needs to be specified twice;
2. The interval is a feature of the hostname, not the policy, which makes it impossible to e.g.
   1. reload pages under `/subpathA/` more frequently than pages under `/subpathB/`;
   2. change the reload interval based on the time of day (e.g. frequent during working hours, but just enough to avoid session timeout over night);

I propose changes in two steps, leading to a simplified format:

First, the interval could become part of the policy:

```
# custom job:
[
  {
    "hostname": "*squash.org.nz",
  }
]

# reload policy:
{
  "*squash.org.nz": {
    "url": "^/sit/"
    "dd": 0,
    "hh": 0,
    "mm": 11,
    "ss": 0
  }
}
```

This would make the custom jobs field completely unnecessary, thus reducing redundancy, error potential, and maintenance effort, because the list of keys of the reload policy dictionary is also the list of hostnames.

But why stop there? Why the distinction between "hostname" and "url", which is actually only the path? Why not create jobs based on the URL? For instance:

```
{
  "^https?://(www\.)?squash\.org\.nz/sit/.+$" : {
    "mm": 3,
    "date": " AM"
  },
  "^https?://(www\.)?squash\.org\.nz/sit/.+$" : {
    "hh": 1,
    "date": " PM"
  },
  "^https?://(www\.)?squash\.org\.nz/news/.+$" : {
    "mm": 1
  }
```

or maybe:

```
{
  "^https?://(www\.)?squash\.org\.nz/sit/.+$" : {
    "policy": { "date": " AM" },
    "interval": "3:00",
  },
  …
}
```

With this format, you simply iterate the list of dictionary keys on every tab/page/rules load and determine the rules that apply, discard those whose policies don't match, and be done.

Make sure to use standard regular expression format regarding delimiters to distinguish those rules from simple wildcard matches, and make sure that anything can be chosen, not just `/`: `|^https://.+|`

**Comment by james-fray** [comment]
Having two sections to configure custom jobs is complex. So I decided to update the custom job to improve URL targeting. The recent push supports both URLPattern (`pt:`) and RegExp (`re:`) matchings. 

See https://add0n.com/tab-reloader.html?v5#faq11

I think this push covers your suggestion.

**Comment by madduck** [comment]
This will do, thanks @james-fray. Note that in the FAQ example, you're missing the leading `pt:` in the final stanza. Is URLPattern the default?

**Comment by james-fray** [comment]
@madduck Yes, The `URLPattern` matching is the default method on 0.5.x. Though I just added the `pt:` prefix to prevent confusion. Thanks!

https://add0n.com/tab-reloader.html?v5r2#faq11

**Comment by james-fray** [comment]
https://github.com/james-fray/tab-reloader/blob/master/v3/api.js#L75-L129

**Comment by madduck** [comment]
I cannot deduce from this code that `pt:` is the default; the default seems to be simple substring matching.

**Comment by james-fray** [comment]
https://github.com/james-fray/tab-reloader/blob/master/v3/reload.js#L7-L12
