### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Omnibrain007** [james-fray/tab-reloader#119]
Is there any translation option in your addon?
Just want to know if it is possible to provide translations and if yes then how it works to submit them?

**Comment by james-fray** [comment]
Yes, you can create the JSON and request pull merge;
https://github.com/james-fray/tab-reloader/tree/master/v3/_locales

**Comment by Omnibrain007** [comment]
Hi,

I started to make a translation for German.
But I found some more phrase inside the addon which are not inside your locale file.
I added them at the end of the attached file behind the data from json file. Not sure if this are all.

Perhaps you can extend you locale file.
[DE-Reloadtabs.txt](https://github.com/james-fray/tab-reloader/files/8653221/DE-Reloadtabs.txt)
.

**Comment by james-fray** [comment]
I just created a new project on "transifex" to have better support for localization. Please join and update the DE locale.

https://www.transifex.com/tb-m/tab-reloader/dashboard/

**Comment by Omnibrain007** [comment]
Done, you now need to grant the access for me to the transifex project.

**Comment by james-fray** [comment]
Done

**Comment by james-fray** [comment]
`de` locale is no included. Thanks for your contribution.
