### ISSUE TITLE
Text alignment

### ISSUE THREAD

**Issue by Omnibrain007** [james-fray/tab-reloader#121]
Just checked new version 0.54 and the alignment is not so good.
I have not checked in Chrome but I use the chrome extension in Opera.
As you see in the first line the field for the time is very big, so the rest will be moved in a second line.

From my point of view the fields for the time and the percentage should be much smaller to align the text in one line

![Relaod](https://user-images.githubusercontent.com/81635182/168523873-acf7e6d2-1a64-491d-85a9-b00850477e9d.JPG)

**Comment by james-fray** [comment]
Please give the latest commit a try to confirm the fix. Thanks!
