### ISSUE TITLE
Feature Request: Auto-Disable Auto-Discarding for Certain URLS/Tabs

### ISSUE THREAD

**Issue by JustaNormalGuy230** [james-fray/tab-reloader#122]
Chrome-based Web Browsers allow users to toggle off-on Auto Discarding at the Tab Level.  This can be accessed via the URL:

chrome://discards/

This disables the algorithm by which a specific tab is rendered dormant to reduce Web Browsing Resources, typically after a period of inactivity.  If a Tab that is open which uses Tab-Reloader is critical to reload successfully each time, it may be mandatory/necessary to not allow the Tab to be discarded at any time by the current Web Browsing Algorithm/Time-Out.  Unfortunately when these particular Web Browsers are initialized/loaded each time, any relaunched Web Tabs are all reset to, "Auto-Discarding Enabled", requiring an end user to re-establish the Auto Discarding to the "Off" or "Disabled" State...

It would be nice if a Check Box for each Tab with a specific URL Match, could be implemented to allow this "off" setting to be set.  I realize that a user may be able to do this via some specific scripting through the current "Tab-Reloader" Application Interface, but this may be beyond the skill level of a typical user...

If someone would like to share their current script coding to do this, by all means, reply away!  My apologies is this was already discussed here or in some other, "Tab-Reloader" Discussion and thank you for making this extension available to Web Browsing Users.

**Comment by james-fray** [comment]
![Screenshot 2022-05-21 at 00 33 56](https://user-images.githubusercontent.com/9897733/169635545-3a432220-2bbf-48ae-9d5f-35bc40ac66eb.png)

I just added a new option to disable discarding if needed.
