### ISSUE TITLE
Use case for sites with tokens

### ISSUE THREAD

**Issue by rloutrel** [james-fray/tab-reloader#124]
I do not come with a solution, but with a use case and some open ideas to discuss:

### Problem description
For my company, I am using a web-platform using rotating licenses with auto disconnection when not actively using it.
This was the original reason for the use of this extension: we have enough keys to not have availability problems but the functionality of this platform is so:
- one use it 2 minutes to navigate inside and get some information (really 2 minutes, because the user-Journey analysis seems to have been ignored yet)
- one do its work out of the platform 2 hours (with this information)
- one comes back and get some more extra-information from the same page (like test results updated from outside)

Unfortunately, the website is technically so developed, that the navigation information is lost (with refresh or auto-disconnect) and one should do the navigation path again. It breaks the working so deeply, that I lost 10 minutes complaining about this tool every time (and the time/nerves of my colleagues around me). Without counting looking for super extension refreshing tokens for me

### Current solution
I am using 2 tabs, on working tab and one with auto reload (to refresh the token), that I set up manually every day, because the json solution accept domain and not full url and I do not want my working window to be refreshed

### Concurrent Ideas
- find a way to distinguish pages of the same domain in https://add0n.com/tab-reloader.html#faq27 (matching regex in the url). Maybe it is already possible, but I did not succeed until today
- develop a "duplicate and close new tab for this page-domain-container":
  - instead of F5 or CTRL-F5, a new tab is opened then closed when loaded
  - I mean with "this page-domain-container", that if I have several pages of the same domain (in a container), it should be done only once per domain and per page (it would not be a problem but avoid too many tabs to pop-up before flying away)
- do some get-call in background to refresh the token and update the cookie

**Comment by james-fray** [comment]
Is this on Firefox?

**Comment by james-fray** [comment]
> Unfortunately, the website is technically so developed, that the navigation information is lost (with refresh or auto-disconnect) and one should do the navigation path again.

Have you tried on Chrome?

**Comment by james-fray** [comment]
On Chrome, you can do regex or [URLPattern](https://developer.mozilla.org/docs/Web/API/URL_Pattern_API) matching; see FAQ11

On FF, the exact URL matching works if I recall correctly.

```js
[
  {
    "url": "https://.....",
    "dd": 0,
    "hh": 0,
    "mm": 1,
    "ss": 30
  }
]
```

**Comment by james-fray** [comment]
btw, have you tried the `Use cache while reloading` option? Does it keep the cookies for you?

**Comment by rloutrel** [comment]
Thank you for your quick replies.

1/ I do not like chromium (for a couple of reasons) and will not change for this reason (my 'quickfix' is acceptable enough)
2/ I will do some more testing later with the url key (instead of domain key). Thank you for the hint! (hope available also in Firefox)
3/ The website provides a kind of navigation within folders and files (it is a bit more complicated, but I want to help you pivcture the context), with a kind of folder tree explorer. The folder tree information (where I am, which folders are folded out/in, ...) is not saved anywhere (no query parameter or cookie or anything else). So F5 or ctrl+f5 (or auto-logout / login) looses the location information within this tree, because the DOM is knew.

**Comment by rloutrel** [comment]
Thank you!
