### ISSUE TITLE
Custom Job: choice to delay randomly the first reload

### ISSUE THREAD

**Issue by rloutrel** [james-fray/tab-reloader#125]
### Use case:
I am opening all windows of a folder at the the same time ("open all Bookmarks" or browser start with previous tabs loaded).
A lot of these pages are using the same period in custom jobs. As a result all reload will be synchronized. For my Firefox, it means a lot of work at the same time (sometime, it result in video freezing), when the rest of the time it is idle.

### Story:
I, as a user of this amazing app, which I could specify (or should it be the default behaviour, with option to disable it?) to delay the first reload iteration at a random time between (start_time) and (start_time + timedelta(days: dd, hours: hh, minutes:mm, seconds: ss)) so that not all tabs are reloading at the same time.

### Extra-information:
I know, there is the "variation"-option, but I prefer having all tabs with static periods which are not synced

**Comment by james-fray** [comment]
Thanks for the suggestion. We are going to have it on the next release. 

![Screenshot](https://user-images.githubusercontent.com/9897733/175862107-97c890d6-ee79-4504-a820-08287c1b9044.png)

**Comment by rloutrel** [comment]
Hi @james-fray!

Thank you for your fast reaction. I assume, the option will be configurable as json custom job. Is this correct?
I see a couple of differences between your screenshot and mine. I assume it is the delta between Firefox and chromium-like implementations (I read it somewhere in your tickets). I suppose, it will also be waiting for the future port. If you need support, I can try to do it, if you give me some inputs like urls of how-tos to read and what your blocker is.
I am more the infrastructure person (python, shell, packaging, ...) than a frontend developer (I can read it, do small modifications but not implement something new). So if it is packaging stuff fell free, if it is a html/css problematic, I won't help

**Comment by james-fray** [comment]
Yes, FF is not yet on 0.5.x. After my recent commit, you can now give it a try on Firefox

1. Download https://github.com/james-fray/tab-reloader/archive/refs/heads/master.zip and extract it locally
2. Open `about:debugging#/runtime/this-firefox` in a browser tab
3. Use the "Load Temporary Add-on" button to locate the `manifest.json` file in the "v3" directory.
