### ISSUE TITLE
play a sound only if a specific HTML element is changed

### ISSUE THREAD

**Issue by pitommasi** [james-fray/tab-reloader#126]
hi, I've read in the faq 19: how to do this?
Let's say I'd like to indentify a div with class "actualContent"...
is the 

`document.getElementsByClassName("actualContent")[0].innerText`

the only way or there's a better one? E.g.: what if there are more "actualContent" elements?

**Comment by james-fray** [comment]
You can alternatively use
```js
const elements = document.querySelectorAll('.actualContent');

const contents = [...elements].map(e => e.innerText)
```

**Comment by pitommasi** [comment]
I'll give it a try... because the way I did it didn't work, it's always playing the sound, even if the content is the same (I've done a compare of the actual innertext)
