### ISSUE TITLE
Missing translation 

### ISSUE THREAD

**Issue by Omnibrain007** [james-fray/tab-reloader#129]
Some translations are missing:

**not in translation available:**
Make sure to press the "Save Options" button!
Restart Extension

**translated but missing in Firefox:**
Default value for "Prevent the tab from discarding"
Default value for "Random delay on the first reload"
Prevent the tab from discarding

**Comment by james-fray** [comment]
Can you please update the https://www.transifex.com/tb-m/tab-reloader/messagesjson/

**Comment by Omnibrain007** [comment]
The two phrases are still missing in transifex;)

- Make sure to press the "Save Options" button!
- Restart Extension

And for the other 3 just the code to integrate in the addon are missing.

**Comment by james-fray** [comment]
Thanks! It is merged now.
