### ISSUE TITLE
Run js code and change detection

### ISSUE THREAD

**Issue by kohanla** [james-fray/tab-reloader#138]
With "run js code" it is possible to transform the content of the tab (for example remove some HTML). Unfortunately "play sound on change" seems to calculate the hash of the page before "run js" which causes the extension to play sound on every load. So it would be great to have an option that told the extension to detect change after "run js". 

I understand that I could probably also do the change detection with "run js code" itself.

**Comment by james-fray** [comment]
I am not able to reproduce this. If the hash code gets calculated before your JS code, the content of it is not affected by the JS code after a reload.

**Comment by kohanla** [comment]
You are right. I can not reproduce this either.

I understand now why I thought there was a bug.

When the pop-up is open and the timer reaches zero and the play sound option is active, then the play-sound event is triggered. I mistakenly assumed that this change was triggered by the code I tested in the popup at the time ... 

Maybe it is possible not to trigger the play-sound event when the pop-up is open?

**Comment by james-fray** [comment]
No, the play sound is only triggered by a content change on reload. It has nothing to do with the popup interface;

https://github.com/james-fray/tab-reloader/blob/master/v3/data/scripts/sha.js#L42

**Comment by kohanla** [comment]
I just tested it again (ff 0.5.9). Currently I have two tabs with "play sound on change". If sound on change is enabled, then the sounds of both tabs will be played when the pop-up is open and a timer of a tab reaches zero. No content change needed.

**Comment by kohanla** [comment]
Some additional information ... when the pop-up is open, the console shows  "Tab Reloader Hash is undefined". This "undefined" is obviously the cause of this issue.

**Comment by james-fray** [comment]
have you tried with the latest commit?

**Comment by kohanla** [comment]
I haven't tried yet. Where is the repo (or build script) for the Firefox version? The v3 folder does not work in Firefox out of the box unfortunately (error background.service_worker is currently disabled).

**Comment by james-fray** [comment]
Use [test.zip](https://github.com/james-fray/tab-reloader/files/10715887/test.zip)

**Comment by kohanla** [comment]
I sideloaded your test.zip 0.6.0, but when the option "play sound" is enabled I get a "red circle with E" after reloading. There are no messages in the console.

For the test I also installed a "fresh" Firefox beta version with no other extensions installed.

And may I ask again? Is there a Firefox repo?

**Comment by kohanla** [comment]
After clicking on the "hosts permission" popup in the options the red circle issue went away ... 

Now while the pop-up is open, I can still see `cannot calculate hash undefined` in the console. But no sound is played while the pop-up is open. So this is basically fixed in your test version.

**Comment by james-fray** [comment]
> And may I ask again? Is there a Firefox repo?

No, You can compile the latest version to m2 using https://github.com/belaviyo/v3tov2

Thanks for the report. The "undefined" issue is also fixed;
 
[test.zip](https://github.com/james-fray/tab-reloader/files/10716268/test.zip)

**Comment by kohanla** [comment]
I tested the new version. The "undefined" issue is fixed indeed. Thanks again.
