### ISSUE TITLE
custom jobs continue to reload after navigating away from specified url

### ISSUE THREAD

**Issue by shonjir** [james-fray/tab-reloader#163]
I have a custom job defined (pt expression) for certain URLs on a website.  Tab reloader is configured to automatically create jobs for matching pages.  However, when I navigate a tab away from the matching URL the refresh job continues to refresh the non-matching page.

Correct behavior:
Tab Reloader should verify the page URL matches the custom job URL and cancel the job if the URL does not match.

Steps to reproduce:

1. Ensure `Always check to install reloading jobs from the JSON object when a new page loads.` is checked
2. Define a custom job with an url pattern

```
[
  {
    "url": "pt:*.example.com/path/to/page?p1=(a|b)",
    "hh": 0,
    "mm": 0,
    "ss": 10,
    "variation": 2,
    "current": true,
    "nofocus": true,
    "cache": true,
    "offline": true,
    "discarded": true,
    "randomize": true
  }
] 
```
3. Navigate to www.example.com/path/to/page?p1=a
4. Observe the job begins
5. Navigate to www.example.com/path/to/page?p1=somethingelse
6. Observe the job continues to refresh

**Comment by james-fray** [comment]
Yes, a custom job works like setting preferences from the popup interface. The extension assigns a job to the tab and does not care about page changes. You can turn off the reloading using the policy section (to temporarily stop the job if the criteria do not match) or even send a `toggle-requested` event to disable the job before navigation happens
