### ISSUE TITLE
save custom job should have URL and URI options

### ISSUE THREAD

**Issue by shonjir** [james-fray/tab-reloader#164]
Current behavior for 'save custom job' is to save only the hostname.  There should be an option to save the URL (without parameters) and/or the full URI (with parameters).  This would allow easy creation of custom jobs for specific pages on a site (or specific selectors on a page).

**Comment by james-fray** [comment]
Thanks for the suggestion. As of the next release you can use Shift + Click and Ctrl + Click for different URL matchings.
