### ISSUE TITLE
Reload tab on double click

### ISSUE THREAD

**Issue by maverick74** [james-fray/tab-reloader#17]
Would be great if we could reload a tab by double clicking it (like other legacy addons used to allow e.g.: https://addons.mozilla.org/pt-PT/firefox/addon/reload-tab-on-double-click/ )

**Comment by james-fray** [comment]
It is impossible at the moment. There is no "ondblclick" listener for tabs in the WebExtension context.

**Comment by maverick74** [comment]
Great.... :( damn "#$%&/() new Mozilla's WE :(

@james-fray Thanks for the reply and clarification :)
