### ISSUE TITLE
"Start Reloading" pop up fails to render properly when source browser window is below a certain width

### ISSUE THREAD

**Issue by Craig-Powell** [james-fray/tab-reloader#175]
Found this on Ubuntu  24.04.1 LTS with Firefox 132.0.1 (64-bit), I have not been able to test elsewhere.  If I have the window shrunk down beneath a certain width when opening tab-reloader I get an empty box.
![Screenshot from 2024-12-05 21-29-41](https://github.com/user-attachments/assets/48026328-15bc-4f80-a883-0e3a33110a1b)
The buttons (at least start reloading) while not visible still work.  And interestingly if I blindly start the reload and then pull up tab-reloader again to see the status, that renders.  You can see that the rest of the popup rendered properly behind that timer and if I cancel the reloading it remains there properly rendered.
![Screenshot from 2024-12-05 21-30-52](https://github.com/user-attachments/assets/6137eab7-3309-4a79-ad6f-936a2d93955b)
If I make the window just slightly wider then the popup renders properly.
![Screenshot from 2024-12-05 21-29-59](https://github.com/user-attachments/assets/5c7b1766-bebf-4595-ab4a-d376244f7d7a)

It seems this may be related to issue #62 but I don't know for sure.  But knowing that whatever starts the render on the display when tab-reloader is active produces proper output maybe this will help to provide a clue to why the not-yet-reloading display fails.

Thanks for your work on this extension!  While I don't use it terribly often, when I do it is a great tool to have!

**Comment by james-fray** [comment]
It seems to be a bug in Firefox on Ubuntu. I tested the extension with very small parent window sizes, and it works fine on my end. Unfortunately, I don't believe there's anything I can do about this issue, as it seems to be related to browser rendering.

![a](https://github.com/user-attachments/assets/7643c36c-b759-4991-bb31-d8d3c7e08d81)

**Comment by Craig-Powell** [comment]
OK, I'll try and test on other systems and follow up.  Thanks!

**Comment by Craig-Powell** [comment]
Haven't gotten to testing elsewhere, but can confirm this is not a tab reloader specific issue.  NoScript extension just did the same thing.  Definitely either something Firefox or Ubuntu.

I guess this could be closed as there is nothing to do in tab reloader.  @james-fray I'll leave that as your call as I don't know if you'd see value in keeping this open for tracking or in the event clues are found that could be thrown the direction of FF/Ubuntu teams.  I can see merit to either, and at minimum this is now in the issue history if someone else encounters it.

I still want to try my planned additional testing to try and get it narrowed down.  I have access to Fedora desktop and Win10 systems which should help to pin if it is FF or Ubuntu generated.

**Comment by james-fray** [comment]
Thank you for the clarification. It's likely that Firefox is not rendering the content properly.
