### ISSUE TITLE
Save preferences

### ISSUE THREAD

**Issue by vkatsikaros** [james-fray/tab-reloader#20]
I'd like to ask if there is a way, or a plan (if currently there isn't a way) to "store" the preference per page. I use MySessions to open existing sessions, and I'd like to somehow make a few pages autoreload automatically.

I hope the question makes sense, let me know if I can provide more information.

**Comment by james-fray** [comment]
Currently after 6 seconds of browser start, old jobs are restored. Isn't this what you are looking for?

**Comment by vkatsikaros** [comment]
Hi @james-fray, just a clarification is this a generic Firefox or a tab-reloader behavior?

My workflow is (1):
* open firefox
* restore a session (which opens a set of saved tabs and windows) using extension MySessions 2.3
* continue using Firefox

To test what you describe I did:
* the above steps (1)
* went to 2 tabs and clicked on tab-reloader -> Enable
* closed Firefox
* did the above steps (1)
* waited for ~30 sec
In the end I didn't see any tabs being "Enabled" for reloading automatically.

Could you give the steps to reproduce the behavior you describe?

**Comment by james-fray** [comment]
I meant if you use the default session manager, the jobs are supposed to be restored. There is no way for the extension to detect when another extension is restoring tabs.

**Comment by vkatsikaros** [comment]
Ah I see, so you think there is no way to do it :(

Just for my education, what do you mean by "jobs" (as in `the jobs are supposed to be restored`)?

**Comment by james-fray** [comment]
If you use Firefox's default session manager to restore tabs, all of them are going to be available when this extension is initiated. After 6 seconds, the extension is going to check all the stored reloading jobs and match each job with all open tabs and if it matches the job is restored.

**Comment by james-fray** [comment]
> Ah I see, so you think there is no way to do it :(

When tabs are restored you need to enable this extension perhaps!

**Comment by vkatsikaros** [comment]
> When tabs are restored you need to enable this extension perhaps!

Thanks! This workaround works.
* I restored the tabs/windows. 
* Then disabled and then enabled the tab-reloader extension.
* Indeed after a few seconds tab-reloader enabled reloading on the expected tabs

**Comment by vkatsikaros** [comment]
A side note, the auto enabling of the reloading, didn't work for `file:///` urls. Could this be an expected webextension behavior (based on the permissions of the extension, etc)?

**Comment by james-fray** [comment]
> didn't work for file:/// urls

This should be fixed on the latest dev version. Please try it and confirm

1. Download https://github.com/james-fray/tab-reloader/archive/master.zip and extract it locally
2. Open about:debugging and point "Load Temporary ... " to src/manifest
3. Reload the extension once you have a few jobs and see if the session restore works for both local and remote pages.

**Comment by james-fray** [comment]
@vkatsikaros I just added a new item to the right-click over the toolbar button to restore reloading jobs. There is no need to restart the extension anymore.

**Comment by vkatsikaros** [comment]
Awesome work @james-fray, I confirm that:
* the "Restore old reloading jobs" behaves as expected:
  * I restore a session with another extension
  * I click this tab-reloader item
  * tab-reloader automatically enables refreshing on the proper pages from the loaded session
* tab-reloader remembers ` file:///` urls too
