### ISSUE TITLE
Scroll Position

### ISSUE THREAD

**Issue by Taurean75** [james-fray/tab-reloader#22]
The scroll position moves to the top when this extension reloads a page.

Please correct it. Thanks!

**Comment by knowguy** [comment]
Can agree with this, I want the page to return to the exact same scroll (horizontal and vertical) that it was.  Working in version 0.2.1, NOT working in 0.2.2 or 0.2.3

**Comment by james-fray** [comment]
If you are on FireFox, in the popup check "Use Cache" option.

**Comment by Taurean75** [comment]
@james-fray, wouldn't it beat the purpose of reloading?

**Comment by Taurean75** [comment]
What's the short code for that?
