### ISSUE TITLE
Context Menu 

### ISSUE THREAD

**Issue by ADG11** [james-fray/tab-reloader#24]
When I first installed tab-reloader (Firefox 57) it created an entry in the context menu, which is extremely useful. This morning that entry was no longer there. I uninstalled and reinstalled the add-on, but still not in the context menu. Is there a way for me to enable that option? Thanks.

**Comment by discgolfer78** [comment]
@james-fray, great ad-on! is there a feature to re-maximize the screen size to "Full screen" after the refresh?

**Comment by raggoo** [comment]
Hi,

Like I  keep 43423455 zillion tabs open and I  look at or click on my tab reloader icon and it says I  have 8 active - HOW do I  easily locate those 8 tabs please?

Or do I  have to manually search for them?

BTW if I  have to manually search for them I  propose a suggestion in the next release that we can click on the count and it would highlight all the tabs it is active on.

Or better still why not a little dot in the corner of the active tabs or some tiny little visual clue where they are hiding LOL! 

Killer addon BTW!
