### ISSUE TITLE
Context Menu (again)

### ISSUE THREAD

**Issue by ADG11** [james-fray/tab-reloader#25]
I posted this yesterday and it was marked "closed" with no response. At the very least, please let me know what's going on:

When I first installed tab-reloader (Firefox 57) it created an entry in the context menu, which is extremely useful. This morning that entry was no longer there. I uninstalled and reinstalled the add-on, but still not in the context menu. Is there a way for me to enable that option? Thanks.

**Comment by james-fray** [comment]
Sorry, GitHub closed the thread when I committed the fix. It is fixed in the newly released version. Just update your extension to the latest version. 

Thanks for the report.

**Comment by ADG11** [comment]
Great – thanks.
