### ISSUE TITLE
Add an option to refresh instead of reload

### ISSUE THREAD

**Issue by tripkin** [james-fray/tab-reloader#26]
I was wondering if it was possible to add a refresh option as well as having a reload, the difference being that the page would remain focused where it is instead of returning to the top of the page. Useful when I am monitoring a statistic and don't have to scroll back down to where it was on each reload - the way the FF refresh button works, but automated.

**Comment by james-fray** [comment]
You must be on FF, if so when defining a job enable the cache option. In Chrome, scroll position is preserved even if Cache is not used.

**Comment by tripkin** [comment]
Yes indeed, I am using FF. Now it works great!  Perhaps a note in the settings dialogue for those of us that insist on using it!  <grin>
Thank you very much!
