### ISSUE TITLE
follow mode

### ISSUE THREAD

**Issue by UlrichScholz** [james-fray/tab-reloader#27]
offer a follow mode that always scrolls to the end of the page, similar to "tail -f". Would be good to view logs.

An extra would be a third mode: stay, which scrolls down the same amount as was selected initially

**Comment by NginUS** [comment]
>a third mode: stay, which scrolls down the same amount as was selected initially

Would use this constantly. Suddenly finding myself back at the top of the page after starting to read something is not desired behavior.

**Comment by james-fray** [comment]
> Would use this constantly. Suddenly finding myself back at the top of the page after starting to read something is not desired behavior.

Your browser is supposed to restore scroll position. What is your browser?

**Comment by UlrichScholz** [comment]
I'm using Firefox, currently version 73.0.1. But "restore scroll position" isn't exactly the same as the mentioned feature, as the page content could increase.  'tail -f' always shows the last line, independent of intermediate content changes

**Comment by james-fray** [comment]
@UlrichScholz we are going to have a new option to scroll to the end.
