### ISSUE TITLE
Feature request: list all active timers

### ISSUE THREAD

**Issue by syldub69** [james-fray/tab-reloader#32]
This is very useful to display the number of active timers on the extension icon in the toolbar.
But, as I have many tabs (more than 200), it is very difficult to identify which tabs have an active timer.
Could you list all the tabs on which the timer is active?
And if we click on one of this tab entry, it could directly activate and focus on the associated tab, that would be really awesome.

**Comment by james-fray** [comment]
We will have the list from the next release. Thanks for the suggestion.
