### ISSUE TITLE
Feature request: automatic job base on URL instead of hostname

### ISSUE THREAD

**Issue by DummySYSTEM** [james-fray/tab-reloader#37]
Right now it is base on hostname so if I want to setup an automatic job for https://twitter.com/i/moments (twitter moments) it will also affect https://twitter.com. If it is base on URL we can have differnet setting for such satuation.

**Comment by james-fray** [comment]
As of the next release you can delete the `hostname` key and append `url` key instead of strict matching.

**Comment by valoricDe** [comment]
is the url field matched just by string, glob or regexp?

**Comment by james-fray** [comment]
@valoricDe strict URL match as far as I remember.
