### ISSUE TITLE
upgraded fx addon today - no long er works

### ISSUE THREAD

**Issue by seasaltseasalt** [james-fray/tab-reloader#4]
Hello: worked beautifully before i upgraded today. now it does not allow me to "enable" the timer for any tab. i have rebooted too. any ideas ?  thankyou

**Comment by james-fray** [comment]
There must be a conflict with another extension. We can either debug the conflict or you can switch to a clean profile if you don't have many extensions installed; http://blog.add0n.com/2016/01/30/how-to-use-firefox-profile-manager.html

**Comment by seasaltseasalt** [comment]
Hello james, Thankyou kindly for your reply.
I have many addons installed. each one is critical. this addon is one of my newest addon.

Yesterday it started working again but no tab indicator/Slider registering on. At least it is now working. so the icon goes orange but no tab counter like it use to. Slider still does not move, even though the icon goes orange which shoes me it is on. though the slider is still showing off.

There were 2 addons the upgraded . I do remember one beingthe CTR addon.  (classic theme)

I understood to debug, one has to uninstall addons, reboot and one by one, install, reboot,  test. That to me will take me a good 4hrs.  I once had to do this for another addon before I realised the effort involved. Crikey!

so i have to put up with faulty addon due to conflict with another addon - as i dont have a spare 4hrs. sorry.

image showing for tab that 2min is on, and working.  just slider is showing OFF + indicator counter previously had prior to upgrade now not showing
![screen shot 2016-07-04 at 12 08 24 pm](https://cloud.githubusercontent.com/assets/12164043/16548365/882f738e-41e0-11e6-9b98-ba2d95b01be5.png)

**Comment by james-fray** [comment]
Let's see that is going wrong. Open Error Console (Ctrl + Shift + J). Clear the console and open Firefox's add-on manager. Disable and re-enable Tab Reloader and see if you get an error message in the console. If yes please take an screenshot of the error and share it here. If not Try to activate tab reloader on a tab and see if an error is generated or not

**Comment by Fritz373** [comment]
HI.
Having same issue.
Here is log:

Could not read chrome manifest 'file:///C:/Program%20Files/Mozilla%20Firefox/chrome.manifest'.
Not enough arguments for chrome manifest directive 'skin', expected 3. chrome.manifest:2:0
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create panel.js:5816:3
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ panel.js:3525:3
not well-formed messages.json:1:1

**Comment by Fritz373** [comment]
Updated FF from ver 46.x to 47.x and reloader appears to be working. Will advise.

**Comment by seasaltseasalt** [comment]
Hi: updated to 47.0.1 few weeks back and has been working beautifully since. Today addon updated automatically and the tab count where tab reloader is set use to be orange and now is grey whether tab is active or not
![screen shot 2016-08-31 at 12 49 08 pm](https://cloud.githubusercontent.com/assets/12164043/18112122/5b696bae-6f79-11e6-8cfc-fb3390d89afd.png)
. is this suppose to happen?. The circle for tabs that tab reloader is set still orange when i click the tab e.g. the tab is active (and tab reloader is set).

**Comment by schomery** [comment]
Yes, the badge color is grayed out as I got some complains that this badge number is very distracting.

**Comment by seasaltseasalt** [comment]
no worries. thankyou james.
