### ISSUE TITLE
Restore does not work in Firefox

### ISSUE THREAD

**Issue by hrdubwd** [james-fray/tab-reloader#45]
This is an extremely useful add-on.  The only problem is that the restore function does not work:
I have restarted a number of times and have had to reset all my key pages, even on Firefox updates.
Something is not quite right.
![Add-ons Manager - Mozilla Firefox-001657](https://user-images.githubusercontent.com/28859375/55565509-db6d6f00-56f1-11e9-8a7b-2c7ddd951c9c.png)
(I am not using SessionManager.)

**Comment by james-fray** [comment]
There will be a new option to adjust when the session restoring activates after a restart. Currently, it is 5 seconds. I would say if you increase this period to like 10 seconds, it will work. Also, note that you can use the right-click item to manually activate the session manager.
