### ISSUE TITLE
Tab reloading after navigator reboot or session load

### ISSUE THREAD

**Issue by JJAY45** [james-fray/tab-reloader#5]
Dear James, good morning,

I use your great plugin on multi-monitor setup, 4 screens & 2 tab with tab reloader enabled (screen n°2 & n°3).
All works fine expected after a navigator crash, or a navigator update or a reboot of the navigator, the tabs are correctly reloaded by the navigator but the screens n°2 & n°3 are loose their settings of tab reloader so they are disabled.
I did some tests and i have realised that when i enabled a tab reloader on the screen n°1 and reload the navigator the settings are correctly reloaded, the tab was reloaded with tab reloader enabled. It's works only with the screen n°1 (main page).

If you have any idea to save all tabs settings, i'm more than interrested! 

Navigator : firefox 47.0
plugins : tab reloader 0.1.2 
gestionnaire de session 0.8.1.2

Thank you for your support.

BR

**Comment by james-fray** [comment]
Before your browser is closed, tab reloader stores all tabs and upon restart of the browser, new jobs are assigned to the stored tabs.

The main issue here is there is no way to store tab itself (or any unique identification associated with this tab). The only identification we have before and after a reboot is tab urls. So it doesn't really mater where tabs are loaded. Tab Reloader just looks for matching URLs.

**Comment by JJAY45** [comment]
Thank you for your explanation.
The tabs on each screen that i reload are the same URLs than previously, so it's strange because when the navigator reboot only the navigator n°1 is reloaded correctly with tab reloader enabled.
The others navigator windows don't seems to be stored.
Is it possible to found a log somewhere in the plugin ?

**Comment by james-fray** [comment]
I think I have got this issue fixed on 0.1.5. Please wait until it gets approved and let me know if you are still observing this issue.

**Comment by JJAY45** [comment]
Okay Thank you James I will keep you informed.
