### ISSUE TITLE
Custom job not working for dkb.de

### ISSUE THREAD

**Issue by orschiro** [james-fray/tab-reloader#50]
@james-fray the new improvements are great!

Custom jobs work pretty well now except for https://www.dkb.de/-

They are not restoring when opening in a new tab despite below settings. 

Any ideas?

https://www.cloudhq.net/screencast/e3be93908c1513.webm

**Comment by orschiro** [comment]
Observed the same on https://www.icloud.com/photos/

**Comment by james-fray** [comment]
Sorry for the late reply. Try `"hostname": "*.dkb.de"`

**Comment by valoricDe** [comment]
I can not confirm that the following works:
```
  [{
    "hostname": "*.dkb.de",
    "dd": 0,
    "hh": 0,
    "mm": 0,
    "ss": 5
  }]
```

**Comment by orschiro** [comment]
Strange. For me it does. Thanks!

**Comment by valoricDe** [comment]
Hey, sry I deleted the comment because I had to check the tickbox `Always check to install...`. Then it worked
