### ISSUE TITLE
Reloader turns off after awhile. 

### ISSUE THREAD

**Issue by xfreakazoidx** [james-fray/tab-reloader#51]
First I'll say I'm not into coding or anything so not sure if there is an easy way to fix this. 

I have the reloader active on a Twitch stream I watch. This way when I am away, it will refresh the page so I am logged into the stream. Problem is sometime I will come back to my PC and the reloader icon is greyed out and off. Is there a way to setup the reloader so it never stops? If it helps I have it reload the page every 30 minutes. Thanks.

**Comment by branditodesign** [comment]
Same issue here, constantly needing to reactivate the timer and also would be great if timers could persist after firefox is relaunched.

**Comment by branditodesign** [comment]
I've just played around with the options, had to tick the 'Always check to install reloading jobs from the JSON object when a new page loads' option to fix it for me, now it even persists after a firefox relaunch.

**Comment by james-fray** [comment]
Please reopen if this is still an issue.
