### ISSUE TITLE
How to reload a tan on select, when it becomes active?

### ISSUE THREAD

**Issue by BobHD** [james-fray/tab-reloader#54]
the Tab Reload On Select add-on does that, but has a nasty bug.
I need a json file which will use active tab, but I don't know the syntax to use.
Something like?
[
  {
    "hostname": "rarbgmirror.com",
    current: Active tab  
  }, 
]
Will that work?

**Comment by james-fray** [comment]
Can you elaborate? Do you want to reload the active tab no matter what the URL is?

**Comment by BobHD** [comment]
Finally "Tab reload on select" works well, maybe after an update. There is an icon you can put on one of the toolbars, and you click on it to enable or disable the feature for the current site, whatever the page.
Exactly what I wanted.
