### ISSUE TITLE
Reload only once after browser launch

### ISSUE THREAD

**Issue by mbatiuk** [james-fray/tab-reloader#58]
HI

I need to reload tabs only once after browser launch. I have separate firefox profile with few tabs opening automatically during launch and sometimes pages get stuck/are not loaded properly and just need one reload. 

Using this extension I can reload based on timer (e.g. 10 seconds) and it works well, but is it possible to reload only once after browser launch and then stop the timer. I guess there should be a possibility to set allowed time of current system time + 15 sec or so, so first reload after 10 sec would happen and following reloads would be stopped until next browser restart?

Alternatively, have 2 time points, 10 sec and 24h or so?

Thanks a lot!

**Comment by james-fray** [comment]
It will be possible as of 0.3.3 release. Please read https://add0n.com/tab-reloader.html?nc#faq17

Since you are on FF, read #18 too.
