### ISSUE TITLE
[Feature Request] Auto reload ALL tabs custom

### ISSUE THREAD

**Issue by A-Sparowe** [james-fray/tab-reloader#59]
I doubt I'm the only person who is used to browsing with 20+ tabs open at any given time right? Yea I forget to close them sometimes but even when I don't forget I'll still typically have enough tabs open to fill the title bar. While I do use a few other extensions to manage it  for when it gets out of hand I'd like to be able to just set up a custom setting that will reload all tabs currently open. 

I'm always leaving stuff open for reference, CSS related stuff, HTML related stuff, Modding related stuff for Skyrim and maybe even a page just for youtube and twitter respectively. Yea it does sound a little lazy of me to even ask if I can somehow achieve this but I figured I'd give it a shot.

**Comment by james-fray** [comment]
Use  the following "Custom Job". Then you can reload all tabs by right-click context menu -> restore old jobs.

```json
[
  {
    "dd": 0,
    "hh": 0,
    "hostname": "*",
    "mm": 1,
    "ss": 0
  }
]
```

**Comment by A-Sparowe** [comment]
Oh wow thanks for this! Once I get some free time I'll test it out.
