### ISSUE TITLE
How to reload (only) all tabs with URL beginning with pattern www.mydomain.com\foobar* ?

### ISSUE THREAD

**Issue by pstein** [james-fray/tab-reloader#60]
Assume I have loaded currently 3 tabs with an URL starting with

www.mydomain.com\foobar......

How can I tell Tab-Reloader to automatically reload every tab (even new one in future) beginning with the mentioned pattern every 20 seconds? All other tabs should not be affected by this setting rule.

Peter

**Comment by james-fray** [comment]
You can use the "Custom Jobs" section to reload tabs with the same hostname (e.g. www.mydomain.com) or the exact same URL with a defined period. Also check "Always check to install reloading jobs..." option
