### ISSUE TITLE
[Feature Request] Main Switch

### ISSUE THREAD

**Issue by Graemek1** [james-fray/tab-reloader#61]
My wish is for a main overall ON-OFF switch so it effectively disables the app when off, then resumes once it's turns on again. It could be located on that main page when you click on the Tab-Reloader icon.  Then, when the markets close I can simply turn off the Reloader App to stop refreshing all those charts and news feeds.

Love the app - very useful.

**Comment by james-fray** [comment]
Thanks for the report. We are going to have a resume button on the right-click context menu as of the next release

![Screen Shot 2020-04-21 at 8 50 56 AM](https://user-images.githubusercontent.com/9897733/79835213-d97a5a80-839d-11ea-865c-0dbf47d5155d.png)

**Comment by Graemek1** [comment]
Ahh Perfect.  Thanks for the reply
Best Regards.

**Comment by Graemek1** [comment]
Hi Again.  Thanks for the added feature.  I noticed there could be a bug unless I don't understand it properly.  If I enable a tab to be reloaded, then later disable that tab, then consequently use the new feature to 'Toggle active reloading tabs' - Stop All, then Enable All, I find that the the tab I had disabled will get re-enabled.  I presume it should only effect the currently enabled tabs.

**Comment by james-fray** [comment]
To cover this use case, we are going to have a new item "Resume previously active jobs" which only resumes old paused jobs without the manual off state.

**Comment by Graemek1** [comment]
Hi, thanks for the info.  I still think a single toggle button to
Enable/Disable the app would be very helpful.  Anyway I do love App - it's
great.
Cheers, Graeme

**Comment by teohhanhui** [comment]
My use case is that I want to save the preferences like the following JSON:

```json
[
  {
    "url": "pt:https://download.copr.fedorainfracloud.org/results/*/builder-live.log",
    "variation": 0,
    "current": false,
    "nofocus": false,
    "cache": true,
    "form": false,
    "offline": true,
    "discarded": false,
    "nodiscard": false,
    "randomize": false,
    "scroll-to-end": true,
    "switch": false,
    "sound": false,
    "sound-value": "1",
    "blocked-words": "",
    "blocked-period": "00:00:00 - 23:59:59",
    "code": "",
    "pre-code": "",
    "hh": 0,
    "mm": 0,
    "ss": 30
  }
]
```

It should use the correct settings when matched, but I want to enable the auto-reload manually.
