### ISSUE TITLE
Options is obscured when Add-on is in Overflow Menu

### ISSUE THREAD

**Issue by cardin** [james-fray/tab-reloader#62]
How to reproduce:
1. Right-click the add-on icon
2. Select "Pin to Overflow Menu"
3. Click on the Overflow Menu and click the add-on icon
4. Observe the options are obscured and therefore unsuable

![Obscured Options](https://i.imgur.com/ruvQl38.png)

Environment:
* Windows 10
* Firefox 76

**Comment by Jonta** [comment]
macOS 10.11.6 is very similar when the Firefox window being narrow forces addon-buttons into overflow

Firefox 76.0.1 64-bit
TR: 0.3.4

**Comment by zman0900** [comment]
Still same problem as of Firefox 81.0.1

**Comment by tikkatek** [comment]
Interestingly, I did not have this issue with earlier versions of Tab Reloader. In this newer interface, I am experiencing this behaviour. While, I love this extension, I am surprised this issue has been open for so long.

![Tab Reloader overflow menu](https://user-images.githubusercontent.com/26571381/180737898-17302365-fb4e-41b4-a2ec-c594d2948760.png)

The design of the configuration menu is not correctly ofsetting the new position of the icon when pinned to the overflow menu, or just needs to have a responsive layout. By moving it out back into the toolbar it does look correct

![Tabl Reloader in toolbar](https://user-images.githubusercontent.com/26571381/180738295-f47111ad-f100-49c0-bffd-222f0b38d730.png)

If anything, this is a workaround, ensuring the icon is not pinned or forced into the overflow menu. If it is forced you can try to configure the toolbar.

My environment:

* MacBook Pro 15-inch 2019
* macOS Monterey (12.0.1)
* Firefox Developer Edition 103.0b9 (64-bit)
* Firefox 102.0.1 (64-bit)
* Using the browser in an external monitor without scaling applied (Dell U2518D 25-inch 2560 x 1440)

**Comment by tikkatek** [comment]
I have noticed have a number of duplicate reports for this issue: #36 (active), #37 (active), #128 (closed)

Apparently, this is fixed in #130 13 days ago, but I am still experiencing this issue. And, yes, I have ensured I am on the latest version.

Would be prudent to merge the issues, to continue investigating this.

**Comment by ray-lothian** [comment]
Honestly, I don't know why Firefox uses two different dimensions for the action popup. Anyhow there will be some enhancements. It is still not perfect, so pull requests are welcome.

<img width="402" alt="Screenshot" src="https://user-images.githubusercontent.com/29911230/180949154-940ccccc-f88d-4da9-bd2b-586ebec7f08a.png">
<img width="395" alt="Screenshot" src="https://user-images.githubusercontent.com/29911230/180949167-e00c3185-4891-4b48-b8ce-11e518f193fa.png">

**Comment by james-fray** [comment]
Thanks @ray-lothian

**Comment by tikkatek** [comment]
Thanks @ray-lothian and @james-fray. I appreciate that you're working on this in your free time. This is still an invaluable util.

**Comment by james-fray** [comment]
Recent versions of Firefox now honor the requested window width and height, so I am closing this issue.
