### ISSUE TITLE
add-on offline

### ISSUE THREAD

**Issue by rickmoua** [james-fray/tab-reloader#63]
Is it possible to download and add the "Tab Reloader" offline?  The machine I want to install has no Internet access.  It is a Windows 10 pro with Firefox 77.0.1.

**Comment by rickmoua** [comment]
Any way to have the reloader automatically enable for any new tab?

**Comment by james-fray** [comment]
> Is it possible to download and add the "Tab Reloader" offline

go to AMO website and right click on the main button. You should be able to get the XPI file. Drop the file to the add-ons manager of the computer with no internet.

**Comment by james-fray** [comment]
> Any way to have the reloader automatically enable for any new tab?

I think you can use the JSON section with the "*" rule for reloading all hostnames. Haven't tried though.

**Comment by rickmoua** [comment]
I’m on this page, but not sure where to download the file.

https://addons.mozilla.org/en-US/firefox/addon/tab-reloader/ <https://addons.mozilla.org/en-US/firefox/addon/tab-reloader/>

**Comment by james-fray** [comment]
With FF browser, open https://addons.mozilla.org/en-US/firefox/addon/tab-reloader/versions/ and right click on "Add to Firefox". Then press "Save..."
