### ISSUE TITLE
regexp not working as expected in reloading policy

### ISSUE THREAD

**Issue by wilsonkf** [james-fray/tab-reloader#64]
regexp are not working as expected

e.g. current time Mon Jul 13 2020 21:00:00 

{
  "\*.google.com": {
    "date": " 2[12]:.*"
  }
}

does not reload

replacing " 2[12]:\*" with
"2[12]:\*"
"21:\*"
"21.\*"
" 2[12]\*" 
still does not work

These work though:
"2[12]\*"
"2[12]:?\*"

**Comment by james-fray** [comment]
use 

```js
(new RegExp(' 2[12]:.*')).test((new Date()).toLocaleString())
```
 to validate if the date format (`new Date()).toLocaleString()`) is correct or not.
