### ISSUE TITLE
[Feature Request] use multiple custom or reloading jobs for the same host.

### ISSUE THREAD

**Issue by todcxtr** [james-fray/tab-reloader#66]
I want to use a different reload interval per path for the same host, like this

http://example.com/page1/ -> 3 hours
http://example.com/page2/ -> 6 hour
http://example.com/page3/test1 -> 20 min
http://example.com/page3/test2 -> 1 hour

In a custom job, only the hostname is distinguishable and the path cannot be specified.
Since the update policy uses a Map keyed to the hostname, multiple definitions for the same host You cannot do this.

I would like to be able to use `"url": "valid regexp"` in a custom job as in the update policy.

**Comment by james-fray** [comment]
how about the new "delay-for" event; https://add0n.com/tab-reloader.html?nc#faq23

You can specify a default period and delay (+/-) from the default value based on the pathname

**Comment by james-fray** [comment]
Please reopen if this method does not work for you.
