### ISSUE TITLE
[Feature Request]: Specific time period refresh

### ISSUE THREAD

**Issue by paladinv** [james-fray/tab-reloader#67]
I would like to request a feature that allows to set the tab-reloader to only auto reload during certain period of time, e.g. only reload every 1 min during 2pm to 3:30pm each day, or reload every 5 min during 6:45pm to 8:15pm and 10pm to 11pm every Tuesday.
Thanks!

**Comment by james-fray** [comment]
You can probably use policies to achieve scheduling: https://add0n.com/tab-reloader.html?nc#faq14

btw, we are going to support a more powerful method as of the next release; https://add0n.com/tab-reloader.html?nc#faq23

Still, none of the above methods are simple to use. So I am going to keep this bug open.
