### ISSUE TITLE
Wrong reloading time

### ISSUE THREAD

**Issue by bdcomp** [james-fray/tab-reloader#7]
Sometimes, wrong (default/minimum?) reloading time used.

My custom reloading time is usually 5 minutes.
Once per about 10 Tab Reloader activation, 10 seconds interval is used, instead of 5 minutes.

Tab Reloader 0.1.5
Firefox 49
Kubuntu 16.04.1 64bit

**Comment by bdcomp** [comment]
common.js, line 164:
`app.timer.setTimeout(restore, 6000);`

Probably this should be not fixed to 6000.

**Comment by james-fray** [comment]
I am not sure why this happens, though I have made some changes in the engine that hopefully have fixed this issue as well. Please re-open if you are still experiencing this on 0.1.6.

**Comment by bdcomp** [comment]
May I ask where is your last development?

**Comment by james-fray** [comment]
https://github.com/james-fray/tab-reloader/commit/48f14a17109e6cc7bc766d6205f6d3db7f5c18b5

**Comment by bdcomp** [comment]
I just had this issue again.
Please reopen it.

Tab Reloader 0.1.6
Firefox 49
Kubuntu 16.04.1 64bit

**Comment by james-fray** [comment]
Is there any way to reproduce this?

**Comment by bdcomp** [comment]
The issue rate is much lower in version 0.1.6 - in fact it's the first time since the update.

It's just happen from time to time, although usually on the first activation only since opening Firefox.

**Comment by james-fray** [comment]
after Firefox startup, the extension restores reloading jobs after 6 seconds. Have you tried to manually set a new job for a tab that already has a job?

**Comment by bdcomp** [comment]
No.
After several minutes (at least) of running Firefox, I tried to set a new timer.
No old or other timers at all.

**Comment by james-fray** [comment]
So when a new timer was set, the extension tried to reload the page after just 10 seconds (when variation was set to zero [default value])?

**Comment by bdcomp** [comment]
No zero - it's 5 minutes, my usual timer value.

**Comment by james-fray** [comment]
There is a new box in the panel view that allows you to define variation in percent as well (to randomize reloading time). I assume this new box is set to zero, right?

**Comment by bdcomp** [comment]
Yes, zero %.
In fact - I never used it.

**Comment by james-fray** [comment]
Okay, I'll see if I can reproduce this bug. If you have found a way to reliably reproduce this, please add a comment here.

**Comment by bdcomp** [comment]
WE version works great.
