### ISSUE TITLE
Add reloading time/remaining time beside each tab under active jobs

### ISSUE THREAD

**Issue by asdaskns** [james-fray/tab-reloader#74]
It would be nice to add the the time was sett, and the remaining time beside each tab under active jobs

It will be easier to know the sett time and the remaining time, instead to have to go to the tab and look it up,

Thanks,

**Comment by chr7** [comment]
I support this, would be very helpful.

**Comment by james-fray** [comment]
Thanks for the suggestion. We are going to have it on the next release.
