### ISSUE TITLE
[Feature Request] Add the ability to use URL instead of Hostname for custom job

### ISSUE THREAD

**Issue by DUN-Cosmos** [james-fray/tab-reloader#76]
Most of the time we just want to reload a specific page and not all page at the same domain.

Please add the ability to use URL instead of Hostname for custom job.

It also happen that we want to reload different page with different period.

**Comment by simsrw73** [comment]
+1 This is one of my primary use-cases. I read a classic style forum that lists conversation threads on the main page which I want to get updated, but when I click through to open the thread on another page I do not want that page to be refreshed while I'm reading. Eg. I'd want this url reloaded when it's open <https://community.logos.com/forums/TopicsActive.aspx>, but not any other urls on that domain.

**Comment by shelbypereira** [comment]
I am also interested in using this for forums,  as an additional feature request (related to the one proposed), it would be nice if we could specifiy the url to refresh.

In many forums there is a page such as ww.abc.com/forum.aspx?threadid=10&page=last

The page=last will auto navigate to the last page.  In fact I would like to specify this is the url to refresh and let it autonavigate to the latest forum,  which would be somthing like  ww.abc.com/forum.aspx?threadid=10&page=12345

however if I can only specify (or select the page to refresh) then I can only refresh ww.abc.com/forum.aspx?threadid=10&page=12345  which will not allow me to automatically go to the last page.

**Comment by james-fray** [comment]
You can use [URLPattern matching](https://developer.mozilla.org/docs/Web/API/URL_Pattern_API) or [regular expression matching](https://developer.mozilla.org/docs/Web/JavaScript/Guide/Regular_Expressions) on the latest release. Read FAQ11; https://add0n.com/tab-reloader.html#faq11
