### ISSUE TITLE
Recieving Fx "Confirm" message on tab reload (for any site I have set reloader too)

### ISSUE THREAD

**Issue by seasaltseasalt** [james-fray/tab-reloader#8]
Hi James.
Have a bit of a pickle.

Upgraded to lastest Firefox on 21st Sept and since the upgrade to Tab-Reloader on 19th (I got it on 21st), I receive this highly annoying "confirm" message from firefox before tab reloader automatically reloads. Never had this in prior version. It means i have to turn off tab-reloader, as this "confirm" message, halts me and forces me to click cancel or resend.  So impossible to have Tab-Reloader on in this state unfortunately.

Confirm Message is received across tabs (e.g. different websites) - for the 2 Tabs I have on reload.
I had these same 2 tabs on prior Firefox, prior Tab-Reloader. 
cookies settings are the same for both websites.

I have no idea where to look.
Screenshot of confirm message attached.

Thankyou James.

![screen shot 2016-09-24 at 12 51 26 pm](https://cloud.githubusercontent.com/assets/12164043/18804911/df5b8b56-8255-11e6-8ca7-9e8dde95251b.png)

**Comment by james-fray** [comment]
This message appears if Firefox is supposed to send data (or already have sent data) to a web server and reloading causes duplicated data to be sent over. Try to open the URL in a new tab and setup a new reloading job.
