### ISSUE TITLE
Reloading policy "url" does not seem to constrain reload

### ISSUE THREAD

**Issue by daveola** [james-fray/tab-reloader#82]
I want to automatically reload my outlook inbox, so I used the custom job:

  {
    "cache": true,
    "code": "console.log('reloaded');",
    "current": true,
    "dd": 0,
    "hh": 0,
    "hostname": "outlook.office.com",
    "mm": 1,
    "ss": 0
  }

And then I added the reloading policy:

{
  "outlook.office.com": {
    "url": "mail/inbox"
  }
}

But any page I open at outlook.office.com, regardless of whether the url contains mail/inbox is still being added to my reload list.

**Comment by james-fray** [comment]
You need a valid regexp. Try:

```json
{
  "outlook.office.com": {
    "url": "mail/\\inbox"
  }
}
```

As of the next release, the icon changes when there is a policy violation.
