### ISSUE TITLE
Don't reload if offline?

### ISSUE THREAD

**Issue by orschiro** [james-fray/tab-reloader#84]
Hi @james-fray,

Is there any way to prevent a tab from reloading if offline?

Thanks!

**Comment by james-fray** [comment]
@orschiro we are going to have a new checkbox on the interface to prevent reloading if offline

@UlrichScholz, #28 is not simple to implement. This extension cannot predict if the server is going to return an error code. And when the error code is generated, there is no way to go back.

**Comment by orschiro** [comment]
Nice, thanks James! :)
