### ISSUE TITLE
Matching URL with arguments/parameters option

### ISSUE THREAD

**Issue by mjeveritt** [james-fray/tab-reloader#85]
As it stands, tab-reloader stores any arguments after the main URL (ie. anything including and following the ?) which can make for some odd resume behaviour for tabs which have changing parameters!
Would it be possible to add an option called something like "complete URL matching" which toggled this matching behaviour on/off - as sometimes the arguments to the URL are redundant, and sometimes they're not?

Example, https://www.metoffice.gov.uk/weather/forecast/ pages have a location code at the end, and an optional ?date= parameter. If you simply want to see the main forecast, and, for example, the date 'stored' in the URL has passed (!) .. tab-reloader presently blindly adds the old URL to its 'remember' list, and adds a new entry when you re-tag the page for reloading. This ends up with quite a long 'history' list of useless URLs to 'remember' .. :smile: 

I recall in another Reloader plugin I used to use - that you could optionally Add a URL to 'fix' the reloading behaviour to force that page should the contents of the Tab 'stray' away from it. This may be a future development, and I shall endeavour to figure out what prompted me to switch to Tab Reloader from this other plugin. I'm guessing some incompatibility with Chrome or such!

**Comment by james-fray** [comment]
> Would it be possible to add an option called something like "complete URL matching" which toggled this matching behaviour on/off - as sometimes the arguments to the URL are redundant, and sometimes they're not?

To automatically reload a hostname, you can simply add a custom job from the options page and the extension only uses the hostname part for matching. something like this:

```json
[
  {
    "dd": 0,
    "hh": 0,
    "hostname": "www.metoffice.gov.uk",
    "mm": 1,
    "ss": 0
  }
]
```

> or example, the date 'stored' in the URL has passed (!) .. tab-reloader presently blindly adds the old URL to its 'remember' list, and adds a new entry when you re-tag the page for reloading.

What is this "remember" list? Do you mean the internal history array that is stored in the `chrome.storage`?
