### ISSUE TITLE
Monitor not Sleeping in Edge Bug

### ISSUE THREAD

**Issue by tc0566** [james-fray/tab-reloader#87]
Seems to be a bug in extension for Microsoft edge. Monitor will not sleep if this extension is enabled in Edge, even with Edge tabbed  down. The problem does not exist in Chrome.

**Comment by james-fray** [comment]
This extension does not have permission to keep the system awake. Note that webpages can request so. For instance on YouTube, when the player is active, the screen is kept awake. 

Please reopen if you have more info to share.
