### ISSUE TITLE
Reload on domain xyz.com but not in xyz/xyz?mail

### ISSUE THREAD

**Issue by lmerega** [james-fray/tab-reloader#89]
Hi all, I would like to create a rule that reloads my tab where there is not the word "mail" in the URL.
The domain is always www.xyz.com/whatever.
It as to be reloaded every 5 minutes.
If it includes the word "mail" (i. e.: www.xyz.com/whatever/mail) it does not have to be reloaded.

Is this possible?

TIA

.luca

**Comment by james-fray** [comment]
You need to define a policy. Something like:

```json
{
  "*": "mail"
}
```

https://add0n.com/tab-reloader.html#faq14
