### ISSUE TITLE
5 min timer resets to -1h 25m

### ISSUE THREAD

**Issue by jamieSquid** [james-fray/tab-reloader#9]
For some URLs, when I set the tab's timer to 5 minutes, the page does refresh after 5 minutes, but then when I go to other tabs and later come back, the timer has reset to -1h 25m.  From then on, it does not refresh that tab.  See attached screenshot.

Here's the URL I was using:
http://radblast.wunderground.com/cgi-bin/radar/WUNIDS_composite?centerlat=29.99333382&centerlon=-90.15777435&radius=90&type=N0R&frame=0&num=6&delay=65&width=1685&height=885&newmaps=1&r=1214255219&smooth=1&rainsnow=1

Tab Reloader 0.1.6
FireFox 50.0

![tabreloaderbug](https://cloud.githubusercontent.com/assets/5349606/20758117/6a962386-b6de-11e6-9c6e-9d8ea5739bfe.png)

**Comment by james-fray** [comment]
Thanks for the report. Please give version 0.1.8 a try and re-open if you still have this issue.

**Comment by jamieSquid** [comment]
Works great now with 0.1.8, thank you!

**Comment by james-fray** [comment]
Perfect!
