### ISSUE TITLE
"Do not reload when Tab is active" doesnt work

### ISSUE THREAD

**Issue by Bubio123** [james-fray/tab-reloader#92]
Hi, I would like to use the function that the tab no longer loads when active. However, this does not work for me. Neither on my old Dell (Chrome), nor on my -company-installed Surface pro 6 (Chrome and IE). Even if I have two windows open next to each other and want to update in one and I'm not in there at all. 
What is going wrong?
Kind regards

**Comment by james-fray** [comment]
Please reopen if you still have the issue on 0.5.x versions.
