### ISSUE TITLE
key press after reload

### ISSUE THREAD

**Issue by jorigel** [james-fray/tab-reloader#97]
Hi,
is it possible to get e.g. <ENTER> pressed after each reload?
And how does the code look like in custom jobs(?) to make that possible?

thank You
jori

**Comment by james-fray** [comment]
You need to write a JS code that fires the click.

```JS
document.querySelector('....').click();
```

When it works, use it on the "Run JS code" section of the popup. Test it once and then use the "Save as a Custom Job" button. You don't need to manually write custom jobs 

P.S.: Firefox does not support this new interface yet.
